export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'AUTH_EMAIL_ALREADY_VERIFIED',
  EMAIL_PENDING_VERIFICATION: 'AUTH_EMAIL_PENDING_VERIFICATION',
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  EMAIL_SAME_PASSWORD: 'AUTH_EMAIL_SAME_PASSWORD',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  NATIONAL_ID_ALREADY_REGISTERED: 'NATIONAL_ID_ALREADY_REGISTERED',

  CONFLICT: 'COMMON_CONFLICT',
  FORBIDDEN: 'COMMON_FORBIDDEN',
  BAD_REQUEST: 'COMMON_BAD_REQUEST',

  //Otp
  OTP_RESEND_TOO_SOON: 'OTP_RESEND_TOO_SOON',
  OTP_RESEND_LIMIT_REACHED: 'OTP_RESEND_LIMIT_REACHED',
  INVALID_OR_EXPIRED_CODE: 'INVALID_OR_EXPIRED_CODE',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  // Common
  VALIDATION_FAILED: 'COMMON_VALIDATION_FAILED',
  RESOURCE_NOT_FOUND: 'COMMON_RESOURCE_NOT_FOUND',
  INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',
  TOO_MANY_REQUESTS: 'COMMON_TOO_MANY_REQUESTS',

  //User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
