export const ErrorCode = {
  // Common
  VALIDATION_FAILED: 'COMMON_VALIDATION_FAILED',
  RESOURCE_NOT_FOUND: 'COMMON_RESOURCE_NOT_FOUND',
  INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',
  TOO_MANY_REQUESTS: 'COMMON_TOO_MANY_REQUESTS',
  CONFLICT: 'COMMON_CONFLICT',
  FORBIDDEN: 'COMMON_FORBIDDEN',
  BAD_REQUEST: 'COMMON_BAD_REQUEST',
  UNAUTHORIZED: 'COMMON_UNAUTHORIZED',

  // Auth
  EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
  EMAIL_ALREADY_VERIFIED: 'AUTH_EMAIL_ALREADY_VERIFIED',
  EMAIL_PENDING_VERIFICATION: 'AUTH_EMAIL_PENDING_VERIFICATION',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  PHONE_ALREADY_REGISTERED: 'AUTH_PHONE_ALREADY_REGISTERED',
  NATIONAL_ID_ALREADY_REGISTERED: 'AUTH_NATIONAL_ID_ALREADY_REGISTERED',

  // Otp
  OTP_RESEND_TOO_SOON: 'OTP_RESEND_TOO_SOON',
  OTP_RESEND_LIMIT_REACHED: 'OTP_RESEND_LIMIT_REACHED',
  INVALID_OR_EXPIRED_CODE: 'OTP_INVALID_OR_EXPIRED_CODE',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
